// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT466bcp4jd45Ak8i984RSHAvsxdewMLE',
    appId: '1:676761857122:web:a6d03d89d0c5ce529cb53b',
    messagingSenderId: '676761857122',
    projectId: 'breathe-fresh-4bf5b',
    authDomain: 'breathe-fresh-4bf5b.firebaseapp.com',
    storageBucket: 'breathe-fresh-4bf5b.appspot.com',
    measurementId: 'G-RRSCFRP88S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCewlLldHanDB-CemWv9nmy0rl4lpCp_Rc',
    appId: '1:676761857122:android:307e6e40e5b43cdc9cb53b',
    messagingSenderId: '676761857122',
    projectId: 'breathe-fresh-4bf5b',
    storageBucket: 'breathe-fresh-4bf5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9v0eMEff0INvItPhk80YaScRN20iNPy8',
    appId: '1:676761857122:ios:917fa8c63a60a5d79cb53b',
    messagingSenderId: '676761857122',
    projectId: 'breathe-fresh-4bf5b',
    storageBucket: 'breathe-fresh-4bf5b.appspot.com',
    iosBundleId: 'com.example.breatheFresh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9v0eMEff0INvItPhk80YaScRN20iNPy8',
    appId: '1:676761857122:ios:2c1d1d9ae411df559cb53b',
    messagingSenderId: '676761857122',
    projectId: 'breathe-fresh-4bf5b',
    storageBucket: 'breathe-fresh-4bf5b.appspot.com',
    iosBundleId: 'com.example.breatheFresh.RunnerTests',
  );
}
